# Generated by Django 4.0 on 2021-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_measure_description_measure_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='short_name',
        ),
        migrations.AddField(
            model_name='measure',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
    ]
